/*
-- Query: SELECT * FROM fit.product
LIMIT 0, 1000

-- Date: 2020-07-05 23:21
*/
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (1,'Assets/Images/mtcreatine.jpg','Creatine','Muscletech','Platinum Creatine','(Unflavored, 80 servs)',4000,20);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (2,'Assets/Images/dymatizewp.jpg','Whey Protein','Dymatize','ISO100 Hydrolyzed Whey Protein','(Chocolate Coconut, 72 servs)',15500,11);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (3,'Assets/Images/prejym.jpg','Pre Workout','JYM','Pre JYM Pre Workout','(Cherry Limeade, 30 servs)',7500,13);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (4,'Assets/Images/evlbcaa.jpg','BCAA','EVLUTION NUTRITION','BCAA Energy','(Cherry Limeade, 30 servs)',4500,14);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (5,'Assets/Images/syntha6.jpg','Whey Protein','BSN','Syntha-6 Whey Protein','(Chocolate Peanut Butter, 48 servs)',10000,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (7,'Assets/Images/cellucorbcaa.jpg','BCAA','Cellucor','Alpha Amino','(Icy Blue Razz, 30 servs)',4700,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (8,'Assets/Images/dymatizesupermass.jpg','Mass Gainer','Dymatize','Super Mass Gainer','(Rich Chocolate, 16 servs)',9000,6);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (9,'Assets/Images/c4.jpg','Pre Workout','Cellucor','C4 Original Pre Workout','(Icy Blue Razz, 35 servs)',7000,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (10,'Assets/Images/cellucorcreatine.jpg','Creatine','Cellucor','COR-Performance Creatine','(Unflavored, 72 servs)',2000,20);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (11,'Assets/Images/dymatizecreatine.jpg','Creatine','Dymatize','Creatine Micronized','(Unflavored, 200 servs)',3800,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (12,'Assets/Images/evlmass.jpg','Mass Gainer','EVLUTION NUTRITION','Stacked Protein Gainer','(Vanilla Icecream, 17 servs)',12000,5);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (13,'Assets/Images/evlpre.jpg','Pre Workout','EVLUTION NUTRITION','ENGN Shred Pre Workout','(Pink Lemonade, 30 servs)',7000,4);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (14,'Assets/Images/evlwhey.jpg','Whey Protein','EVLUTION NUTRITION','Stacked Protein','(Chocolate Decadense, 49 servs)',10000,4);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (15,'Assets/Images/jymwhey.jpg','Whey Protein','JYM','Pro JYM Protein Powder','(Chocolate Cookie Crunch, 45 servs)',11000,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (16,'Assets/Images/massjym.jpg','Mass Gainer','JYM','Mass JYM Mass Gainer Protein Powder','(Tahitian Vanilla Bean, 30 servs)',12500,5);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (17,'Assets/Images/mpwhey.jpg','Whey Protein','MusclePharm','Combat Whey Protein Powder','(Chocolate Milk, 42 servs)',9500,5);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (18,'Assets/Images/mtbcaa.jpg','BCAA','Muscletech','Amino Build Next Gen Amino Acids','(Icy Rocket Freeze, 30 servs)',5500,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (19,'Assets/Images/mtcelltech.jpg','Creatine','Muscletech','CELL-TECH','(Fruit Punch, 56 servs)',9500,8);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (20,'Assets/Images/mtmasstech.jpg','Mass Gainer','Muscletech','Mass-Tech Extreme 2000','(Triple Chocolate Brownie, 18 servs)',19000,8);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (21,'Assets/Images/xtendwhey.jpg','Choose...','Xtend','Pro Whey Protein Isolate','(Chocolate Lava Cake, 64 servs)',15000,10);
INSERT INTO `` (`productID`,`productImageDir`,`productType`,`productBrand`,`productName`,`productDescription`,`productPrice`,`numInStock`) VALUES (44,'Assets/Images/xtendwhey.jpg','Whey Protein','Xtend','Pro Whey Protein Isolate','(Chocolate Lava Cake, 64 servs)',15000,10);
